name: build-and-test-rpn
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        version: [1.24.5]
        os: [ubuntu-latest, windows-latest, macos-latest]
    name: Build
    runs-on: ${{ matrix.os }}
    steps:
    - name: Set up Go ${{ matrix.version }}
      uses: actions/setup-go@v5
      with:
        go-version: '${{ matrix.version }}'
      id: go

    - name: checkout
      uses: actions/checkout@v5

    - name: build
      run: make buildlocal

    - name: test
      run: make test

  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24
      - uses: actions/checkout@v5
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          skip-cache: true
